### ISSUE TITLE
Get a logo

### ISSUE THREAD

**Issue by sempiternael** [wdnf/wdnf.github.io#4]
User submission @ tamkoro
What does everyone think?
https://media.discordapp.net/attachments/678611525698715668/679718108763783188/unknown.png

**Comment by Pavan-da-Coder** [comment]
I don't know about that logo's font-It looks slightly extreme

**Comment by Pavan-da-Coder** [comment]
I am mainly talking about the N-it looks very...out of place

**Comment by Pavan-da-Coder** [comment]
But, since this is gonna go as a favicon and a general logo, I think it's ok
