### ISSUE TITLE
Create navigation menu

### ISSUE THREAD

**Issue by sempiternael** [wdnf/wdnf.github.io#5]
Need a navigation menu. Use CSS for any dropdowns. Should be 100% responsive.

**Comment by Pavan-da-Coder** [comment]
Oliver said he was annoyed that the header is...not using the best CSS technologies-I think he wants to create a new header via CSS Flexbox and Media Queries

**Comment by sempiternael** [comment]
He does @Pavan-da-Coder. He also wants the menu just be pure-css and not use JavaScript, you can find some more information regarding that style of menu by checking out some of his work like https://natours.netlify.com/

**Comment by Pavan-da-Coder** [comment]
Ok since noone is fixing/making a new header I'm gonna make a proper one with Visual Studio Code.
