### ISSUE TITLE
Separate Files

### ISSUE THREAD

**Issue by Pavan-da-Coder** [wdnf/wdnf.github.io#7]
We need multiple files for multiple pages-A css doc and html doc for the home page, a separate css and html doc for News, Contact, Etc. 
![image](https://user-images.githubusercontent.com/61098154/74890856-4f892380-5353-11ea-8213-571c88554860.png)
I suggest we replace Dropdown with a list of languages we are helping people with in the website(like HTML, CSS, JS) all in a list so they appear next to each other(because we have the space on the header bar).

**Comment by sempiternael** [comment]
Should work on getting a full index up first. Content is crucial, but only when it makes sense.

**Comment by JohnBostick** [comment]
those at the top are placeholders for anything we want to put there. a language selection could be put there
