### ISSUE TITLE
Base layout

### ISSUE THREAD

**Issue by JohnBostick** [wdnf/wdnf.github.io#8]
Need to create a layout for the website. Im going to draw a layout and send it when done. @pfinnegane

**Comment by JohnBostick** [comment]
![layout](https://user-images.githubusercontent.com/48634417/74961513-32e4fe00-53dc-11ea-86ee-b5959fd3776d.png)
simple layout

**Comment by sempiternael** [comment]
Question: Why have a navbar if we have a sidebar?
Yes, it makes some sense, but, why not simply throw everything in one. and do a pseudo-header as margin / branding container?
